const fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
const test=require('node:test'),assert=require('node:assert/strict');
const {runtime}=require('./helpers/inventory-runtime.cjs');

test('adaptador: sin fechas respalda cuatro originales y no inventa un corte',()=>{const r=runtime();r.ctx.procesarHistoricoPT();assert.equal(r.status().status,'RESPALDADO_PENDIENTE_FECHAS');assert.equal(r.state(),null);assert.equal(r.archive.folders[0].files.filter(f=>f.name.endsWith('.xlsx')).length,4);assert.equal(r.conversions(),0);});
test('adaptador: carga aceptada es recuperable y su repetición no reconvierte ni cambia el estado',()=>{const r=runtime();r.declare();r.ctx.procesarHistoricoPT();assert.equal(r.state().loads.length,1);assert.equal(r.conversions(),4);assert.ok(r.state().current.dataId);const pointer=r.props.get('PCC_HIST_STATE_FILE');r.ctx.procesarHistoricoPT();assert.equal(r.conversions(),4);assert.equal(r.props.get('PCC_HIST_STATE_FILE'),pointer);assert.equal(r.status().status,'SIN_CAMBIOS');});
test('adaptador: cambiar un Excel invalida las fechas del paquete anterior',()=>{const r=runtime();r.declare();r.source.invEU.bytes=Buffer.from(r.source.invEU.bytes.toString().replace('Prenda','Prenda nueva'));r.ctx.procesarHistoricoPT();assert.equal(r.status().status,'RESPALDADO_PENDIENTE_FECHAS');assert.equal(r.state(),null);});
test('adaptador: el formulario rechaza un paquete cambiado mientras el usuario lo completa',()=>{const r=runtime();const f=r.ctx.datosFormularioHistoricoPT();r.source.invEU.bytes=Buffer.from('nuevo contenido');assert.throws(()=>r.ctx.registrarCargaHistoricaPT({fingerprint:f.fingerprint,cutoff:'2026-09-16',from:'2026-09-01',to:'2026-09-16'}),/cambiaron/);});
test('adaptador: un fallo de escritura conserva la publicación anterior y permite reintentar',()=>{const r=runtime();r.declare();r.ctx.procesarHistoricoPT();const previous=r.props.get('PCC_HIST_STATE_FILE');r.source.invEU.bytes=Buffer.from(r.source.invEU.bytes.toString().replace('Prenda','Prenda nueva'));r.declare();r.setFault('corte.json');assert.throws(()=>r.ctx.procesarHistoricoPT(),/Fallo simulado/);assert.equal(r.props.get('PCC_HIST_STATE_FILE'),previous);r.setFault(null);r.ctx.procesarHistoricoPT();assert.equal(r.state().loads.length,2);});
test('adaptador: cambios durante conversión impiden aceptar una mezcla de archivos',()=>{const r=runtime();r.declare();r.setOnConvert(()=>r.source.invEU.modified++);r.ctx.procesarHistoricoPT();assert.equal(r.state(),null);assert.equal(r.status().status,'ARCHIVOS_CAMBIARON');});
test('adaptador: paquete sin integridad confirmada se archiva sin reemplazar el inventario aceptado',()=>{const r=runtime();r.declare(false);r.ctx.procesarHistoricoPT();assert.equal(r.state().loads.length,1);assert.equal(r.state().current,null);});
test('adaptador: HTML del formulario tiene JavaScript compilable',()=>{const html=fs.readFileSync('apps-script/inventory-history/CargaHistorica.html','utf8');for(const m of html.matchAll(/<script>([\s\S]*?)<\/script>/g))assert.doesNotThrow(()=>new vm.Script(m[1]));});
