const test=require('node:test'),assert=require('node:assert/strict');
const H=require('../scripts/inventory-history/core.js');
const invHeader=['Referencia','Desc. item','Detalle ext. 2','Detalle ext. 1','Bodega','Existencia','Cant. comprometida','Cant. disponible'];
const movHeader=['Referencia','Detalle ext. 2','Detalle ext. 1','Bodega','Fecha','Tipo docto.','Entradas (inv.)','Salidas (inv.)','Neto (inv.)','Costo entradas (prom.)','Costo salidas (prom.)','Costo neto (prom.)'];
const inv=(units=10)=>[invHeader,['001','Prenda','M','01','PT001',units,2,units-2]];
const mov=(type='EOP',incoming=8,outgoing=0)=>[movHeader,['001','M','01','PT001','2026-09-10',type,incoming,outgoing,incoming-outgoing,incoming*25,outgoing*25,(incoming-outgoing)*25]];
function files(){return Object.fromEntries(['EU','TEX'].flatMap(c=>[['inv'+c,{hash:'inv'+c,meta:{cutoff:'2026-09-16',complete:true},rows:inv()}],['mov'+c,{hash:'mov'+c,meta:{from:'2026-09-01',to:'2026-09-16',complete:true},rows:mov()}]]));}
const opts={today:'2026-09-16'};
test('histórico: fechas estrictas y números ambiguos se rechazan',()=>{assert.equal(H.date('8/9/2026'),'2026-09-08');for(const d of ['2026-02-30','2026-13-01','hoy',''])assert.throws(()=>H.date(d));assert.throws(()=>H.number('1.200,50','costo'));assert.equal(H.number(1200.50,'costo'),1200.50);});
test('histórico: corte por empresa y fecha real, nunca hora de ejecución',()=>{const f=files();let batch=H.prepare(f,opts);assert.equal(batch.cutoff,'2026-09-16');assert.equal(batch.inventory[0].cutoff,'2026-09-16');f.invTEX.meta.cutoff='2026-09-15';assert.throws(()=>H.prepare(f,opts),/diferentes/);});
test('histórico: archivos incompletos, corte futuro y movimientos fuera del rango bloquean',()=>{let f=files();delete f.invEU;assert.throws(()=>H.prepare(f,opts),/Falta archivo/);f=files();f.invEU.meta.cutoff=f.invTEX.meta.cutoff='2026-09-17';assert.throws(()=>H.prepare(f,opts),/futuro/);f=files();f.movEU.meta.to='2026-09-09';assert.throws(()=>H.prepare(f,opts),/fuera del período/);});
test('histórico: el límite del ERP y el conteo declarado detectan cargas sospechosas',()=>{let f=files();assert.throws(()=>H.prepare(f,{...opts,rowLimit:1}),/límite/);f.invEU.meta.expectedRows=2;assert.throws(()=>H.prepare(f,opts),/Cantidad de filas/);});
test('histórico: stock concilia por SKU y empresa sin mezclar referencias iguales',()=>{const b=H.prepare(files(),opts);assert.equal(b.totals.EU.units,10);assert.equal(b.totals.TEX.units,10);const rows=inv();rows.push(rows[1]);assert.throws(()=>H.inventory(rows,'EU','2026-09-16'),/duplicado/);rows.pop();rows[1][7]=15;assert.throws(()=>H.inventory(rows,'EU','2026-09-16'),/no concilia/);});
test('histórico: costo y antigüedad no se inventan cuando el inventario no los informa',()=>{const b=H.prepare(files(),opts);assert.equal(b.totals.EU.value,null);assert.equal(b.inventory[0].age,null);assert.equal(b.inventory[0].value,null);});
test('histórico: costos de movimiento son totales y el unitario se divide por unidades',()=>{const r=H.movements(mov(),'EU','2026-09-01','2026-09-16').records[0];assert.equal(r.costIn,200);assert.equal(r.unitCostIn,25);});
test('histórico: conserva entradas y salidas en TRI, ENS, EOP y AIC',()=>{for(const type of ['TRI','ENS','EOP','AIC']){const r=H.movements(mov(type,8,3),'EU','2026-09-01','2026-09-16').records[0];assert.equal(r.in,8);assert.equal(r.out,3);assert.equal(r.net,5);}});
test('histórico: dos movimientos de misma clave y fecha permanecen separados',()=>{const rows=mov();rows.push(rows[1].slice());const r=H.movements(rows,'EU','2026-09-01','2026-09-16');assert.equal(r.records.length,2);assert.ok(r.warnings.length);});
test('histórico: documento y línea repetidos bloquean sin eliminar silenciosamente',()=>{const rows=mov();rows[0]=rows[0].concat(['Numero documento','Linea documento']);rows[1]=rows[1].concat(['A1','1']);rows.push(rows[1].slice());assert.throws(()=>H.movements(rows,'EU','2026-09-01','2026-09-16'),/duplicados/);});
test('histórico: selección exacta de encabezados evita confundir descripción con referencia',()=>{const rows=inv();rows[0]=['Desc. referencia',...rows[0]];rows[1]=['otro',...rows[1]];assert.equal(H.inventory(rows,'EU','2026-09-16').records[0].ref,'001');});
test('histórico: sustitución completa conserva meses anteriores y no duplica solapes',()=>{
 const previous=[{company:'EU',date:'2026-05-01',in:1},{company:'EU',date:'2026-09-10',in:7},{company:'TEX',date:'2026-09-10',in:3}];
 const b=H.prepare(files(),opts);const once=H.mergeMovements(previous,b),twice=H.mergeMovements(once,b);
 assert.deepEqual(twice,once);assert.equal(once.length,3);assert.equal(once[0].date,'2026-05-01');
});
test('histórico: rango parcial no borra cobertura aceptada; rango completo vacío sí elimina registros obsoletos',()=>{
 const previous=[{company:'EU',date:'2026-09-10',in:7}];const b={movements:[],coverage:[{company:'EU',from:'2026-09-01',to:'2026-09-16',complete:false}]};assert.deepEqual(H.mergeMovements(previous,b),previous);b.coverage[0].complete=true;assert.deepEqual(H.mergeMovements(previous,b),[]);
});
test('histórico: cerrar exige corte fin de mes, ambas empresas y exportaciones completas',()=>{
 const f=files();f.invEU.meta.cutoff=f.invTEX.meta.cutoff='2026-09-30';f.movEU.meta.to=f.movTEX.meta.to='2026-09-30';const b=H.prepare(f,{today:'2026-10-01'});
 assert.equal(H.monthlyStatus(b,'2026-09-01'),'CIERRE_EXISTENCIAS');assert.equal(H.monthlyStatus(b,'2026-09-16'),'PRIMER_MES_PARCIAL');b.coverage[0].complete=false;assert.equal(H.monthlyStatus(b,'2026-09-01'),'CIERRE_PENDIENTE_COBERTURA');b.coverage[0].complete=true;b.inventoryComplete=false;assert.equal(H.monthlyStatus(b,'2026-09-01'),'CIERRE_PENDIENTE_COBERTURA');
});
test('histórico: la unión de rangos detecta días faltantes y no confunde ausencia con cero',()=>{const ranges=[{company:'EU',from:'2026-09-01',to:'2026-09-15',complete:true},{company:'EU',from:'2026-09-17',to:'2026-09-30',complete:true}];assert.equal(H.covers(ranges,'EU','2026-09-01','2026-09-30'),false);ranges[1].from='2026-09-16';assert.equal(H.covers(ranges,'EU','2026-09-01','2026-09-30'),true);});
test('histórico: repetición conserva fecha, corrección crea versión y no altera las anteriores',()=>{const b=H.prepare(files(),opts),s=H.accept(null,b,'a','t1');assert.equal(H.accept(s,b,'a','t2'),s);const c=H.accept(s,b,'b','t2');assert.equal(s.loads.length,1);assert.equal(c.loads.length,2);assert.equal(c.current.id,'b');assert.equal(c.loads[0].processedAt,'t1');assert.throws(()=>H.accept(c,{...b,cutoff:'2026-09-15'},'c','t3'),/anterior/);});
test('histórico: una carga anterior al corte actual no lo reemplaza',()=>{let b=H.prepare(files(),opts),s=H.accept(null,b,'a','t1');s=H.accept(s,{...b,cutoff:'2026-09-20'},'b','t2');s=H.accept(s,{...b,cutoff:'2026-09-18'},'c','t3');assert.equal(s.current.id,'b');assert.equal(s.months['2026-09'].id,'b');assert.equal(s.loads.length,3);});
test('histórico: nombres reconocibles y metadatos vinculados al contenido, nunca lastModified',()=>{assert.deepEqual(H.metadata('INVENTARIO PT EU.xlsx','', 'hash'),{});assert.equal(H.metadata('INV EU corte 2026-09-16.xlsx','', 'hash').cutoff,'2026-09-16');assert.deepEqual(H.metadata('INV.xlsx',JSON.stringify({pcc:{cutoff:'2026-09-16'}}),'new'),{});assert.throws(()=>H.metadata('INV.xlsx',JSON.stringify({pcc:{sha256:'old',cutoff:'2026-09-16'}}),'new'),/otra versión/);});
