const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),test=require('node:test');
function runtime(account='client@example.test',denied=null){
 const props=new Map(),triggers=[];let folders=0,menus=0;
 const svc={getProperty:k=>props.get(k)||null,setProperty(k,v){props.set(k,v);}};
 const ctx=vm.createContext({CFG:{OUTPUT_ID:'sheet',XLSX_INVENTARIO_EU:'a',XLSX_INVENTARIO_TEX:'b',XLSX_MOVIMIENTOS_EU:'c',XLSX_MOVIMIENTOS_TEX:'d'},Logger:{log(){}},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock(){}})},Session:{getEffectiveUser:()=>({getEmail:()=>account})},PropertiesService:{getScriptProperties:()=>svc},DriveApp:{getFileById:id=>{if(id===denied)throw Error('Sin acceso a la fuente');return {getName:()=>id,getOwner:()=>({getEmail:()=> 'client@example.test'})};},createFolder:()=>{folders++;return {getId:()=> 'archive'};},getFolderById:()=>({getName:()=> 'archive'})},ScriptApp:{getProjectTriggers:()=>triggers,newTrigger:handler=>({forSpreadsheet:id=>({onOpen:()=>({create:()=>triggers.push({getHandlerFunction:()=>handler,spreadsheet:id})})})})},menuHistoricoPT:()=>menus++,pccHistConfig_:()=>JSON.parse(props.get('PCC_HIST_CONFIG'))});
 vm.runInContext(fs.readFileSync('apps-script/inventory-history/Integration.gs','utf8'),ctx);
 return {ctx,props,triggers,counts:()=>({folders,menus})};
}
test('instalación: la cuenta colaboradora no crea respaldos ni activadores del cliente',()=>{const r=runtime('developer@example.test');assert.throws(()=>r.ctx.configurarPilotoHistoricoPT(),/cuenta propietaria/);assert.equal(r.counts().folders,0);assert.equal(r.triggers.length,0);assert.equal(r.props.size,0);});
test('instalación: comprueba acceso a todas las fuentes antes de crear recursos',()=>{const r=runtime('client@example.test','d');assert.throws(()=>r.ctx.configurarPilotoHistoricoPT(),/Sin acceso/);assert.equal(r.counts().folders,0);assert.equal(r.props.size,0);});
test('instalación: propietario configura una vez, conserva ajustes y solo instala el menú',()=>{const r=runtime();r.ctx.configurarPilotoHistoricoPT();const c=JSON.parse(r.props.get('PCC_HIST_CONFIG'));assert.equal(c.files.invEU,'a');c.quietMinutes=25;r.props.set('PCC_HIST_CONFIG',JSON.stringify(c));r.ctx.configurarPilotoHistoricoPT();assert.equal(r.counts().folders,1);assert.equal(r.triggers.length,1);assert.equal(r.triggers[0].getHandlerFunction(),'menuHistoricoPT');assert.equal(JSON.parse(r.props.get('PCC_HIST_CONFIG')).quietMinutes,25);assert.equal(r.props.get('PCC_HIST_STATE_FILE'),undefined);});
