const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const html=fs.readFileSync('inventario_pt.html','utf8'),code=html.slice(html.indexOf('const XF_ICON'),html.indexOf('// Cerrar panel flotante'));
function runtime(){const elements={},checks=[],ctx=vm.createContext({Set,console,window:{},document:{getElementById:id=>elements[id],querySelectorAll:()=>checks}});vm.runInContext(code,ctx);return {ctx,elements,checks,run:s=>vm.runInContext(s,ctx)};}
test('filtros históricos: opciones de toda la fuente aunque solo se pinten 50 filas',()=>{const r=runtime();r.run("XF_VALUE_PROVIDERS.hist=()=>Array.from({length:845},(_,i)=>String(i));");assert.equal(r.run("xfGetVals('hist',1).size"),845);});
test('filtros históricos: búsqueda parcial conserva selecciones que no están visibles',()=>{const r=runtime();r.run("XF_VALUE_PROVIDERS.hist=()=>['EU','TEX','OTRA'];XF_STATE.hist_0=new Set();");r.checks.push({value:'EU',checked:false});r.run("xfUpdateApplied('hist_0','hist',0)");assert.equal(r.run("[...XF_STATE.hist_0].sort().join(',')"),'OTRA,TEX');});
test('filtros históricos: desmarcar último valor da cero resultados y permite seleccionar de nuevo',()=>{const r=runtime();r.run("XF_VALUE_PROVIDERS.hist=()=>['EU','TEX'];XF_STATE.hist_0=new Set(['EU']);");r.checks.push({value:'EU',checked:false},{value:'TEX',checked:false});r.run("xfUpdateApplied('hist_0','hist',0)");assert.equal(r.run("xfFilterRows('hist',[{company:'EU'}],r=>[r.company]).length"),0);r.checks[1].checked=true;r.run("xfUpdateApplied('hist_0','hist',0)");assert.equal(r.run("[...XF_STATE.hist_0].join(',')"),'TEX');});
test('filtros históricos: filtros de columnas se intersectan antes de paginar',()=>{const r=runtime();r.run("XF_STATE.hist_0=new Set(['EU']);XF_STATE.hist_1=new Set(['001']);");assert.equal(r.run("xfFilterRows('hist',[['EU','001'],['TEX','001'],['EU','002']],r=>r).length"),1);});
test('filtros históricos: textos del ERP se escapan en el menú y el marcador Ninguno no aparece',()=>{const r=runtime();r.elements['xf-panel-items']={innerHTML:''};r.elements['xf-panel-count']={textContent:''};r.run("XF_VALUE_PROVIDERS.hist=()=>['<img src=x onerror=alert(1)>'];XF_STATE.hist_0=new Set(['\\x00__NONE__\\x00']);xfPopulate('hist_0','hist',0,'renderHistoricoTable','');");assert.ok(r.elements['xf-panel-items'].innerHTML.includes('&lt;img'));assert.ok(!r.elements['xf-panel-items'].innerHTML.includes('<img'));assert.ok(!r.elements['xf-panel-items'].innerHTML.includes('__NONE__'));assert.equal(r.elements['xf-panel-count'].textContent,'0 de 1 activos');});
test('scripts históricos y HTML compilan después de integrar filtros',()=>{new vm.Script(fs.readFileSync('inventory-history-view.js','utf8'));for(const m of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);});
