const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('crypto');
const M=require('../inventory-history-model.js');
const {runtime}=require('./helpers/inventory-runtime.cjs');
function batch(cutoff,units=10,coverage=true){return {cutoff,inventoryComplete:true,inventory:[{company:'EU',ref:'001',description:'Prenda',warehouse:'PT001',units,committed:2,available:units-2},{company:'TEX',ref:'001',description:'Prenda',warehouse:'TI004',units:5,committed:1,available:4}],coverage:['EU','TEX'].map(company=>({company,from:'2026-09-01',to:cutoff,complete:coverage})),movements:[{company:'EU',warehouse:'PT001',date:cutoff,in:5,out:2},{company:'TEX',warehouse:'TI004',date:cutoff,in:1,out:3}]};}
function readPublic(r){const d=JSON.parse(r.book.getSheetByName('INV_Hist_Control').getRange(1,1).getValue());const text=r.book.getSheetByName('INV_Hist_Datos').getRange(d.row,1,d.count,1).getValues().map(r=>r[0].slice(1)).join('');assert.equal(crypto.createHash('sha256').update(text).digest('hex'),d.hash);return JSON.parse(text);}
test('consulta: primer mes parcial, ningún dato anterior al inicio y empresas separadas',()=>{const q=M.apply(null,batch('2026-09-17'),'a','2026-09-17');assert.equal(q.ledger.length,2);assert.equal(q.cuts[0].summary[0].units,10);const months=M.monthly(q,'2026-09-17');assert.equal(months.length,1);assert.equal(months[0].status,'Primer mes parcial');assert.equal(months[0].units,15);assert.equal(months[0].in,6);assert.equal(M.monthly(q,'2026-09-17','EU','PT001')[0].units,10);assert.equal(M.monthly(q,'2026-09-17','EU','TI004')[0].units,0);});
test('consulta: solapamientos sustituyen períodos completos, vacío corrige y parcial no elimina',()=>{let q=M.apply(null,batch('2026-09-17'),'a','2026-09-17');const b=batch('2026-09-19');q=M.apply(q,b,'b','2026-09-17');assert.equal(q.ledger.length,2);assert.ok(q.ledger.every(r=>r.date==='2026-09-19'));const incomplete={...b,inventoryComplete:false,movements:[],coverage:b.coverage.map(c=>({...c,complete:false}))};const old=q;q=M.apply(q,incomplete,'c','2026-09-17');assert.deepEqual(q.ledger,old.ledger);assert.equal(q.cuts.length,2);q=M.apply(q,{...b,movements:[]},'d','2026-09-17');assert.equal(q.ledger.length,0);assert.equal(q.cuts.length,2);});
test('consulta: corrige la misma fecha y conserva cortes más recientes al recibir uno pasado',()=>{let q=M.apply(null,batch('2026-09-17'),'a','2026-09-17');q=M.apply(q,batch('2026-09-20'),'b',q.startCutoff);q=M.apply(q,batch('2026-09-18'),'c',q.startCutoff);q=M.apply(q,batch('2026-09-17',30),'d',q.startCutoff);assert.deepEqual(q.cuts.map(c=>c.cutoff),['2026-09-17','2026-09-18','2026-09-20']);assert.equal(q.cuts[0].summary[0].units,30);assert.deepEqual(M.apply(q,batch('2026-09-17'),'d',q.startCutoff),q);});
test('consulta: vacío con cobertura es cero; sin cobertura es null y no inventa cierre',()=>{const q=M.apply(null,batch('2026-09-17',10,false),'a','2026-09-17');const m=M.monthly(q,'2026-09-30')[0];assert.equal(m.in,null);assert.equal(m.stockStatus,'Último corte disponible');assert.equal(m.cutoff,'2026-09-17');});
test('consulta: referencias con ceros, bodegas y variación sin porcentaje con base cero',()=>{const rows=M.groupStock([...batch('2026-09-17').inventory,...batch('2026-09-17').inventory]);assert.equal(rows.length,2);assert.equal(rows[0].ref,'001');assert.equal(M.filterStock(rows,'EU','PT001','prenda')[0].units,20);assert.equal(M.compare(rows,[]).percent,null);assert.equal(M.compare(rows,null),null);});
test('publicación: conserva datos privados y solo publica una consulta verificada',()=>{const r=runtime();r.enablePublication();r.declare();r.ctx.procesarHistoricoPT();const q=readPublic(r);assert.equal(q.cuts.length,1);assert.equal(q.cuts[0].cutoff,'2026-09-16');assert.equal(q.cuts[0].summary.reduce((n,r)=>n+r.units,0),20);for(const key of ['folderId','dataId','sourceRow','sources','processed','processedAt','costIn'])assert.ok(!JSON.stringify(q).includes('"'+key+'"'));const rows=r.book.getSheetByName('INV_Hist_Datos').getLastRow();r.ctx.procesarHistoricoPT();assert.equal(r.book.getSheetByName('INV_Hist_Datos').getLastRow(),rows);assert.equal(r.props.get('PCC_HIST_PUBLISHED_STATE'),r.props.get('PCC_HIST_STATE_FILE'));});
test('publicación: fallo de manifiesto conserva consulta anterior; SIN_CAMBIOS reintenta',()=>{const r=runtime();r.enablePublication();r.declare();r.ctx.procesarHistoricoPT();const old=readPublic(r),control=r.book.getSheetByName('INV_Hist_Control').getRange(1,1).getValue();r.source.invEU.bytes=Buffer.from(r.source.invEU.bytes.toString().replace('10,2,8','20,2,18'));r.declare();r.setFault('INV_Hist_Control');r.ctx.procesarHistoricoPT();assert.equal(r.state().loads.length,2);assert.equal(r.book.getSheetByName('INV_Hist_Control').getRange(1,1).getValue(),control);assert.deepEqual(readPublic(r),old);assert.match(r.props.get('PCC_HIST_PUBLICATION_STATUS'),/REVISAR_PUBLICACION/);r.setFault(null);r.ctx.procesarHistoricoPT();assert.equal(readPublic(r).cuts[0].summary.reduce((n,r)=>n+r.units,0),30);});
test('publicación: fallo de detalle no cambia puntero ni pierde la carga privada',()=>{const r=runtime();r.enablePublication();r.declare();r.setFault('INV_Hist_Datos');r.ctx.procesarHistoricoPT();assert.equal(r.state().loads.length,1);assert.equal(r.props.get('PCC_HIST_QUERY_FILE'),undefined);assert.equal(r.book.getSheetByName('INV_Hist_Control'),undefined);r.setFault(null);r.ctx.procesarHistoricoPT();assert.equal(readPublic(r).cuts.length,1);});
test('publicación: reanuda desde cache privado tras agotar tiempo sin cambiar índice',()=>{const r=runtime();r.declare();r.ctx.procesarHistoricoPT();r.enablePublication();r.ctx.pccHistPublish_(0);assert.equal(r.props.get('PCC_HIST_PUBLICATION_STATUS'),'CONTINUAR_PUBLICACION');assert.equal(r.book.getSheetByName('INV_Hist_Control'),undefined);r.ctx.pccHistPublish_(Date.now()+10000);assert.equal(readPublic(r).cuts.length,1);});
test('publicación: fragmentos no ejecutan fórmulas ni pierden Unicode o delimitadores',()=>{const r=runtime(),s=r.book.insertSheet('test');const value={schema:1,text:'=IMPORTXML("url"); 🧵'.repeat(3000)};const d=r.ctx.pccHistAppendQuery_(s,value);assert.ok(d.count>1);const rows=s.getRange(d.row,1,d.count,1).getValues();assert.ok(rows.every(r=>r[0][0]==='j'));assert.deepEqual(JSON.parse(rows.map(r=>r[0].slice(1)).join('')),value);});
